name: ci

on:
  push:
    branches:
      - staging
      - production
      - master

jobs:
  build:
    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      DENO_INSTALL: "/Users/runner/.local"
      DENO_LATEST_VERSION: "v0.27.0"
      GIT_PUSHER_BOT: ${{ secrets.GIT_PUSHER_BOT }}
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install

    - name: install deno
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_LATEST_VERSION

    - name: git clone deno-drash
      run: |
        git clone https://github.com/drashland/deno-drash.git ../deno-drash

    - name: copy .ts files
      run: |
        cp deps.sample.ts deps.ts
        cp conf/app.ci.ts conf/app.ts

    - name: configure git
      run: |
        git remote rm origin
        git remote add origin https://$GIT_PUSHER_BOT@github.com/drashland/deno-drash-docs.git
        git config user.email $CI_USER_EMAIL
        git config user.name $CI_USER_NAME
        git pull origin master

    - name: deploy staging
      if: github.ref == 'refs/heads/staging'
      run: |
        export DENO_DRASH_DOCS_ENVIRONMENT="staging"
        export PATH=$DENO_INSTALL/bin:$PATH
        console/compile_assets
        console/run_webpack --env.environment=$DENO_DRASH_DOCS_ENVIRONMENT
        console/compile_ejs_templates
        npm run staging

    - name: deploy production
      if: github.ref == 'refs/heads/production'
      run: |
        export PATH=$DENO_INSTALL/bin:$PATH
        npm run production

    - name: update long-running branches
      if: github.ref == 'refs/heads/master'
      run: |
        git pull origin
        git checkout staging
        git merge origin/master
        git checkout production
        git merge origin/master
