# Example request: curl -XPOST -u "${{ secrets.CI_USER_NAME }}:${{ secrets.CI_USER_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/drashland/copyright-free/dispatches --data '{"event_type": "update_docs", "client_payload": { "module_to_update": "drash" }}'
on:
  repository_dispatch:
    types: [update_docs]

jobs:

  bump-vue-versions:

    if: ${{ github.event.event_type }} == "update_docs"

    strategy:
      matrix:
        deno: ["1.2.2"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Update Versions in Webpack Config
        run: deno run --allow-read --allow-net --allow-write scripts/bump_module_versions_in_config.ts --module ${{ github.event.client_payload.module_to_update }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.CI_USER_PAT }}
          commit-message: bump versions in webpack config
          title: bump versions in webpack config
          body: This was auto-generated by GitHub Actions.
          branch: bump-webpack-config-versions