name: production

on:
  push:
    branches:
      - production

jobs:
  build:

    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      DENO_INSTALL: "/Users/runner/.local"
      CI_USER_PAT: ${{ secrets.CI_USER_PAT }}

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install

    - name: install deno
      run: |
        console/install_deno

    - name: git clone deno-drash
      run: |
        git clone https://github.com/drashland/deno-drash.git ../deno-drash

    - name: configure git
      run: |
        console/configure_git

    - name: deploy production
      if: github.ref == 'refs/heads/production'
      run: |
        export DENO_DRASH_DOCS_ENVIRONMENT="production"
        console/set_common_env_vars
        console/copy_config_files
        console/compile_assets
        console/run_webpack --env.environment=$DENO_DRASH_DOCS_ENVIRONMENT
        console/compile_ejs_templates
        cp index.html versions/$DENO_DRASH_LATEST_RELEASE/index.html
        cp index.html versions/$DENO_DRASH_LATEST_RELEASE/index.html
        git add index.html
        git add public/*
        git commit -m "production build ($(date))"
        git push origin HEAD:master
