name: production

on:
  push:
    branches:
      - production

jobs:
  build:

    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      DENO_INSTALL: "/Users/runner/.local"
      CI_USER_PAT: ${{ secrets.CI_USER_PAT }}

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install deno
      run: |
        cd docs
        console/install_deno

    - name: npm install
      # if: github.event_name == 'push'
      run: |
        cd docs
        npm install

    - name: add git user drashbot
      run: |
        cd docs
        console/add_git_user_drashbot

    - name: build production
      if: github.ref == 'refs/heads/production'
      run: |
        export PATH="$DENO_INSTALL/bin:$PATH"
        cd docs
        console/production_build

    - name: commit production
      if: github.ref == 'refs/heads/production'
      run: |
        cd docs
        console/production_commit

    - name: push production to master
      if: github.ref == 'refs/heads/production'
      run: |
        git push origin HEAD:master
