name: staging

on:
  push:
    branches:
      - staging


env:
  CI: true
  CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
  CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
  DENO_INSTALL: "/Users/runner/.local"
  CI_USER_PAT: ${{ secrets.CI_USER_PAT }}

jobs:

  clone_repo:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

  deno_install:
    needs: [clone_repo]
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: install deno
      run: |
        cd docs
        console/install_deno

  clone_deno_drash:
    needs: [clone_repo]
    runs-on: macOS-latest
    steps:
    - name: git clone deno-drash
      run: |
        git clone https://github.com/drashland/deno-drash.git ../deno-drash

  build:
    needs: [deno_install, clone_deno_drash]
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        cd docs
        npm install

    - name: build staging
      if: github.ref == 'refs/heads/staging'
      run: |
        export PATH="$DENO_INSTALL/bin:$PATH"
        cd docs
        console/staging_build

  deploy:
    needs: [build]
    runs-on: macOS-latest

    steps:

    - uses: actions/checkout@v1

    - name: add git user drashbot
      run: |
        cd docs
        console/add_git_user_drashbot

    - name: commit staging
      if: github.ref == 'refs/heads/staging'
      run: |
        cd docs
        console/staging_commit

    - name: push staging to master
      if: github.ref == 'refs/heads/staging'
      run: |
        cd docs
        git push origin HEAD:master
