# Example on how to trigger this:
# - name: Send Event to Website to Update Versions
#   run: |
#     curl -XPOST -u "${{ secrets.CI_USER_NAME }}:${{ secrets.CI_USER_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/drashland/copyright-free/dispatches --data '{"event_type": "update_docs", "client_payload": { "module_to_update": "drash", "version": "${{ github.event.release.tag_name }}" }}'

name: update-docs

on:
  repository_dispatch:
    types: [update_docs]

jobs:

  update-versions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update Versions for Docs
        run: node scripts/update_module_versions.js --module ${{ github.event.client_payload.module_to_update }} --version ${{ github.event.client_payload.version }}

      - name: Create Pull Request
        if: ${{ github.event.event_type }} == "update_docs"
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.CI_USER_PAT }}
          commit-message: bump versions
          title: bump versions
          body: This was auto-generated by GitHub Actions.
          branch: update-versions
          base: staging